language: java
jdk:
  - openjdk7
branches:
  only:
    - master
before_install: 'mvn -version'
install: 'mvn clean install -Pfull -DskipTests'

after_success: |
  if [ -n "$GITHUB_API_KEY" ]; then
    cd "$TRAVIS_BUILD_DIR"
  	cd target/
  	mkdir git
    cd git
  	git init
    git checkout -b builds
    ls -lart
    mv ../analyzer-next-*-with-dependencies.jar .
    git add .
    git -c user.name='travis' -c user.email='travis' commit -m bulild
  fi