language: java
jdk:
  - openjdk7
branches:
  only:
    - master
before_install: 'mvn -version'
install: 'mvn clean install -Pfull -DskipTests'

after_success: |
  if [ -n "$GITHUB_API_KEY" ]; then
    cd "$TRAVIS_BUILD_DIR"
  	cd target/
  	mkdir git
  	git init
    git checkout -b builds
    mv ../analyzer-next-*-with-dependencies.jar .
  fi